name: Create and publish SHACL API Docker image

on:
  release:
    type: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

        # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
        # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@15c905b16b06416d2086efa066dd8e3a35cc7f98
        
        # https://github.com/marketplace/actions/get-version
      - name: Get release version
        id: get_version
        uses: reloc8/action-latest-release-version@1.0.0

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .docker/
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.get_version.outputs.latest-release }}
          outputs: type=image
